title: Noor Ahmed Raza Pirwani
email: noorahmedpirwani@gmail.com
subtitle:  UX Strategist & Digital Fabricator
description: >-
  I help teams transform complexity into intuitive, goal-driven experiences. My background in digital fabrication sharpens my ability to think systematically — from concept to execution.

baseurl: "/portfolio"
url: "https://noorpirwani.github.io"
author:
street_address:
city: Karachi
state: Sindh
zip_code: 74600
country: Pakistan
phone: (+92) 321-2330567

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

socials:
  GitHub: https://github.com/noorpirwani
  GitLab: https://gitlab.fabcloud.org/noorahmedraza.pirwani
  LinkedIn: https://pk.linkedin.com/in/noor-ahmed-pirwani

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-feed

sass:
  style: compressed

# Custom collections
collections:
  experience:
    output: true
    sort_by: start_date
  education:
    output: true
    sort_by: end_date
  uxcase:
    output: true
    permalink: /work/:name/

# Exclude folders you don’t want Jekyll to build
exclude:
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - elements.md
  - generic.md
  - landing.md
  - README.md
  - .DS_Store
  - _drafts
  - _posts
  - 404.md
  - all_posts.md